### PR TITLE
Transmit cookies on redirect

### PR DESCRIPTION
**Pull request by Farkal**
Fix https://github.com/jkhsjdhjs/node-fetch-cookies/issues/4

### CODE REVIEW

**Comment by Farkal** [comment]
I have made the adjustments you ask for ;)
For the typo i suggest you to add a .prettierrc (i use prettier) it's easier to get the right format (just ask vscode to format the file after adding some code and can be checked with eslint pre-commit hook)

**Comment by jkhsjdhjs** [comment]
Thanks! Also thanks for the hint with `prettier`, didn't know about it. Will check it out!
Now there's just one more issue in the code: `options` on line 41 can be `null` now, since you changed the condition for `wantFollow`. This will result in an error, when all supplied cookie jars are empty.

**Comment by Farkal** [comment]
Yeah sorry :disappointed: it should be fixed

**Comment by jkhsjdhjs** [comment]
Thanks, merged!

**Pull request merged**
